// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cached_network_parameters.proto

#ifndef PROTOBUF_cached_5fnetwork_5fparameters_2eproto__INCLUDED
#define PROTOBUF_cached_5fnetwork_5fparameters_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)
#include "net/base/net_export.h"

namespace net {

// Internal implementation detail -- do not call these.
void NET_EXPORT_PRIVATE protobuf_AddDesc_cached_5fnetwork_5fparameters_2eproto();
void protobuf_AssignDesc_cached_5fnetwork_5fparameters_2eproto();
void protobuf_ShutdownFile_cached_5fnetwork_5fparameters_2eproto();

class CachedNetworkParameters;

enum CachedNetworkParameters_PreviousConnectionState {
  CachedNetworkParameters_PreviousConnectionState_SLOW_START = 0,
  CachedNetworkParameters_PreviousConnectionState_CONGESTION_AVOIDANCE = 1
};
NET_EXPORT_PRIVATE bool CachedNetworkParameters_PreviousConnectionState_IsValid(int value);
const CachedNetworkParameters_PreviousConnectionState CachedNetworkParameters_PreviousConnectionState_PreviousConnectionState_MIN = CachedNetworkParameters_PreviousConnectionState_SLOW_START;
const CachedNetworkParameters_PreviousConnectionState CachedNetworkParameters_PreviousConnectionState_PreviousConnectionState_MAX = CachedNetworkParameters_PreviousConnectionState_CONGESTION_AVOIDANCE;
const int CachedNetworkParameters_PreviousConnectionState_PreviousConnectionState_ARRAYSIZE = CachedNetworkParameters_PreviousConnectionState_PreviousConnectionState_MAX + 1;

// ===================================================================

class NET_EXPORT_PRIVATE CachedNetworkParameters : public ::google::protobuf::MessageLite {
 public:
  CachedNetworkParameters();
  virtual ~CachedNetworkParameters();

  CachedNetworkParameters(const CachedNetworkParameters& from);

  inline CachedNetworkParameters& operator=(const CachedNetworkParameters& from) {
    CopyFrom(from);
    return *this;
  }

  static const CachedNetworkParameters& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CachedNetworkParameters* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CachedNetworkParameters* other);

  // implements Message ----------------------------------------------

  CachedNetworkParameters* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CachedNetworkParameters& from);
  void MergeFrom(const CachedNetworkParameters& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef CachedNetworkParameters_PreviousConnectionState PreviousConnectionState;
  static const PreviousConnectionState SLOW_START = CachedNetworkParameters_PreviousConnectionState_SLOW_START;
  static const PreviousConnectionState CONGESTION_AVOIDANCE = CachedNetworkParameters_PreviousConnectionState_CONGESTION_AVOIDANCE;
  static inline bool PreviousConnectionState_IsValid(int value) {
    return CachedNetworkParameters_PreviousConnectionState_IsValid(value);
  }
  static const PreviousConnectionState PreviousConnectionState_MIN =
    CachedNetworkParameters_PreviousConnectionState_PreviousConnectionState_MIN;
  static const PreviousConnectionState PreviousConnectionState_MAX =
    CachedNetworkParameters_PreviousConnectionState_PreviousConnectionState_MAX;
  static const int PreviousConnectionState_ARRAYSIZE =
    CachedNetworkParameters_PreviousConnectionState_PreviousConnectionState_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // optional string serving_region = 1;
  inline bool has_serving_region() const;
  inline void clear_serving_region();
  static const int kServingRegionFieldNumber = 1;
  inline const ::std::string& serving_region() const;
  inline void set_serving_region(const ::std::string& value);
  inline void set_serving_region(const char* value);
  inline void set_serving_region(const char* value, size_t size);
  inline ::std::string* mutable_serving_region();
  inline ::std::string* release_serving_region();
  inline void set_allocated_serving_region(::std::string* serving_region);

  // optional int32 bandwidth_estimate_bytes_per_second = 2;
  inline bool has_bandwidth_estimate_bytes_per_second() const;
  inline void clear_bandwidth_estimate_bytes_per_second();
  static const int kBandwidthEstimateBytesPerSecondFieldNumber = 2;
  inline ::google::protobuf::int32 bandwidth_estimate_bytes_per_second() const;
  inline void set_bandwidth_estimate_bytes_per_second(::google::protobuf::int32 value);

  // optional int32 max_bandwidth_estimate_bytes_per_second = 5;
  inline bool has_max_bandwidth_estimate_bytes_per_second() const;
  inline void clear_max_bandwidth_estimate_bytes_per_second();
  static const int kMaxBandwidthEstimateBytesPerSecondFieldNumber = 5;
  inline ::google::protobuf::int32 max_bandwidth_estimate_bytes_per_second() const;
  inline void set_max_bandwidth_estimate_bytes_per_second(::google::protobuf::int32 value);

  // optional int64 max_bandwidth_timestamp_seconds = 6;
  inline bool has_max_bandwidth_timestamp_seconds() const;
  inline void clear_max_bandwidth_timestamp_seconds();
  static const int kMaxBandwidthTimestampSecondsFieldNumber = 6;
  inline ::google::protobuf::int64 max_bandwidth_timestamp_seconds() const;
  inline void set_max_bandwidth_timestamp_seconds(::google::protobuf::int64 value);

  // optional int32 min_rtt_ms = 3;
  inline bool has_min_rtt_ms() const;
  inline void clear_min_rtt_ms();
  static const int kMinRttMsFieldNumber = 3;
  inline ::google::protobuf::int32 min_rtt_ms() const;
  inline void set_min_rtt_ms(::google::protobuf::int32 value);

  // optional int32 previous_connection_state = 4;
  inline bool has_previous_connection_state() const;
  inline void clear_previous_connection_state();
  static const int kPreviousConnectionStateFieldNumber = 4;
  inline ::google::protobuf::int32 previous_connection_state() const;
  inline void set_previous_connection_state(::google::protobuf::int32 value);

  // optional int64 timestamp = 7;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 7;
  inline ::google::protobuf::int64 timestamp() const;
  inline void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:net.CachedNetworkParameters)
 private:
  inline void set_has_serving_region();
  inline void clear_has_serving_region();
  inline void set_has_bandwidth_estimate_bytes_per_second();
  inline void clear_has_bandwidth_estimate_bytes_per_second();
  inline void set_has_max_bandwidth_estimate_bytes_per_second();
  inline void clear_has_max_bandwidth_estimate_bytes_per_second();
  inline void set_has_max_bandwidth_timestamp_seconds();
  inline void clear_has_max_bandwidth_timestamp_seconds();
  inline void set_has_min_rtt_ms();
  inline void clear_has_min_rtt_ms();
  inline void set_has_previous_connection_state();
  inline void clear_has_previous_connection_state();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::std::string* serving_region_;
  ::google::protobuf::int32 bandwidth_estimate_bytes_per_second_;
  ::google::protobuf::int32 max_bandwidth_estimate_bytes_per_second_;
  ::google::protobuf::int64 max_bandwidth_timestamp_seconds_;
  ::google::protobuf::int32 min_rtt_ms_;
  ::google::protobuf::int32 previous_connection_state_;
  ::google::protobuf::int64 timestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void NET_EXPORT_PRIVATE protobuf_AddDesc_cached_5fnetwork_5fparameters_2eproto_impl();
  #else
  friend void NET_EXPORT_PRIVATE protobuf_AddDesc_cached_5fnetwork_5fparameters_2eproto();
  #endif
  friend void protobuf_AssignDesc_cached_5fnetwork_5fparameters_2eproto();
  friend void protobuf_ShutdownFile_cached_5fnetwork_5fparameters_2eproto();

  void InitAsDefaultInstance();
  static CachedNetworkParameters* default_instance_;
};
// ===================================================================


// ===================================================================

// CachedNetworkParameters

// optional string serving_region = 1;
inline bool CachedNetworkParameters::has_serving_region() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CachedNetworkParameters::set_has_serving_region() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CachedNetworkParameters::clear_has_serving_region() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CachedNetworkParameters::clear_serving_region() {
  if (serving_region_ != &::google::protobuf::internal::GetEmptyString()) {
    serving_region_->clear();
  }
  clear_has_serving_region();
}
inline const ::std::string& CachedNetworkParameters::serving_region() const {
  return *serving_region_;
}
inline void CachedNetworkParameters::set_serving_region(const ::std::string& value) {
  set_has_serving_region();
  if (serving_region_ == &::google::protobuf::internal::GetEmptyString()) {
    serving_region_ = new ::std::string;
  }
  serving_region_->assign(value);
}
inline void CachedNetworkParameters::set_serving_region(const char* value) {
  set_has_serving_region();
  if (serving_region_ == &::google::protobuf::internal::GetEmptyString()) {
    serving_region_ = new ::std::string;
  }
  serving_region_->assign(value);
}
inline void CachedNetworkParameters::set_serving_region(const char* value, size_t size) {
  set_has_serving_region();
  if (serving_region_ == &::google::protobuf::internal::GetEmptyString()) {
    serving_region_ = new ::std::string;
  }
  serving_region_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CachedNetworkParameters::mutable_serving_region() {
  set_has_serving_region();
  if (serving_region_ == &::google::protobuf::internal::GetEmptyString()) {
    serving_region_ = new ::std::string;
  }
  return serving_region_;
}
inline ::std::string* CachedNetworkParameters::release_serving_region() {
  clear_has_serving_region();
  if (serving_region_ == &::google::protobuf::internal::GetEmptyString()) {
    return NULL;
  } else {
    ::std::string* temp = serving_region_;
    serving_region_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
    return temp;
  }
}
inline void CachedNetworkParameters::set_allocated_serving_region(::std::string* serving_region) {
  if (serving_region_ != &::google::protobuf::internal::GetEmptyString()) {
    delete serving_region_;
  }
  if (serving_region) {
    set_has_serving_region();
    serving_region_ = serving_region;
  } else {
    clear_has_serving_region();
    serving_region_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyString());
  }
}

// optional int32 bandwidth_estimate_bytes_per_second = 2;
inline bool CachedNetworkParameters::has_bandwidth_estimate_bytes_per_second() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CachedNetworkParameters::set_has_bandwidth_estimate_bytes_per_second() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CachedNetworkParameters::clear_has_bandwidth_estimate_bytes_per_second() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CachedNetworkParameters::clear_bandwidth_estimate_bytes_per_second() {
  bandwidth_estimate_bytes_per_second_ = 0;
  clear_has_bandwidth_estimate_bytes_per_second();
}
inline ::google::protobuf::int32 CachedNetworkParameters::bandwidth_estimate_bytes_per_second() const {
  return bandwidth_estimate_bytes_per_second_;
}
inline void CachedNetworkParameters::set_bandwidth_estimate_bytes_per_second(::google::protobuf::int32 value) {
  set_has_bandwidth_estimate_bytes_per_second();
  bandwidth_estimate_bytes_per_second_ = value;
}

// optional int32 max_bandwidth_estimate_bytes_per_second = 5;
inline bool CachedNetworkParameters::has_max_bandwidth_estimate_bytes_per_second() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CachedNetworkParameters::set_has_max_bandwidth_estimate_bytes_per_second() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CachedNetworkParameters::clear_has_max_bandwidth_estimate_bytes_per_second() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CachedNetworkParameters::clear_max_bandwidth_estimate_bytes_per_second() {
  max_bandwidth_estimate_bytes_per_second_ = 0;
  clear_has_max_bandwidth_estimate_bytes_per_second();
}
inline ::google::protobuf::int32 CachedNetworkParameters::max_bandwidth_estimate_bytes_per_second() const {
  return max_bandwidth_estimate_bytes_per_second_;
}
inline void CachedNetworkParameters::set_max_bandwidth_estimate_bytes_per_second(::google::protobuf::int32 value) {
  set_has_max_bandwidth_estimate_bytes_per_second();
  max_bandwidth_estimate_bytes_per_second_ = value;
}

// optional int64 max_bandwidth_timestamp_seconds = 6;
inline bool CachedNetworkParameters::has_max_bandwidth_timestamp_seconds() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CachedNetworkParameters::set_has_max_bandwidth_timestamp_seconds() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CachedNetworkParameters::clear_has_max_bandwidth_timestamp_seconds() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CachedNetworkParameters::clear_max_bandwidth_timestamp_seconds() {
  max_bandwidth_timestamp_seconds_ = GOOGLE_LONGLONG(0);
  clear_has_max_bandwidth_timestamp_seconds();
}
inline ::google::protobuf::int64 CachedNetworkParameters::max_bandwidth_timestamp_seconds() const {
  return max_bandwidth_timestamp_seconds_;
}
inline void CachedNetworkParameters::set_max_bandwidth_timestamp_seconds(::google::protobuf::int64 value) {
  set_has_max_bandwidth_timestamp_seconds();
  max_bandwidth_timestamp_seconds_ = value;
}

// optional int32 min_rtt_ms = 3;
inline bool CachedNetworkParameters::has_min_rtt_ms() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CachedNetworkParameters::set_has_min_rtt_ms() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CachedNetworkParameters::clear_has_min_rtt_ms() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CachedNetworkParameters::clear_min_rtt_ms() {
  min_rtt_ms_ = 0;
  clear_has_min_rtt_ms();
}
inline ::google::protobuf::int32 CachedNetworkParameters::min_rtt_ms() const {
  return min_rtt_ms_;
}
inline void CachedNetworkParameters::set_min_rtt_ms(::google::protobuf::int32 value) {
  set_has_min_rtt_ms();
  min_rtt_ms_ = value;
}

// optional int32 previous_connection_state = 4;
inline bool CachedNetworkParameters::has_previous_connection_state() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CachedNetworkParameters::set_has_previous_connection_state() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CachedNetworkParameters::clear_has_previous_connection_state() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CachedNetworkParameters::clear_previous_connection_state() {
  previous_connection_state_ = 0;
  clear_has_previous_connection_state();
}
inline ::google::protobuf::int32 CachedNetworkParameters::previous_connection_state() const {
  return previous_connection_state_;
}
inline void CachedNetworkParameters::set_previous_connection_state(::google::protobuf::int32 value) {
  set_has_previous_connection_state();
  previous_connection_state_ = value;
}

// optional int64 timestamp = 7;
inline bool CachedNetworkParameters::has_timestamp() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CachedNetworkParameters::set_has_timestamp() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CachedNetworkParameters::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CachedNetworkParameters::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 CachedNetworkParameters::timestamp() const {
  return timestamp_;
}
inline void CachedNetworkParameters::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace net

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cached_5fnetwork_5fparameters_2eproto__INCLUDED
